- name: Add nvidia-docker gpg apt key
  become: true
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Add nvidia-docker repository to apt sources
  become: true
  apt_repository:
    repo: "{{ item }}"
    filename: nvidia-docker
    mode: 0644
    update_cache: yes
    state: present
  with_items:
      # https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list
      - "deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64 /"
      - "deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64 /"
      - "deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64 /"

- name: Install nvidia-docker
  become: true
  apt:
    name: nvidia-docker2
    update_cache: yes
    state: present
